ERROR_CATALOG = {
    1: "Sesion invalida. Recarga e intenta de nuevo.",
    2: "Contrasena incorrecta.",
    3: "Usuario no registrado.",
    100: "Configuracion de base de datos incompleta.",
    101: "Configuracion de base de datos invalida.",
    102: "Configuracion de conexion no soportada.",
    103: "No se pudo autenticar contra la base de datos.",
    104: "No se encontro el driver de SQL Server.",
    105: "No se pudo conectar al servidor SQL.",
    106: "Falta una dependencia del sistema.",
    200: "Accion no permitida.",
    201: "No tienes permiso para modificar usuarios.",
    202: "No tienes permiso para esa empresa.",
    203: "No tienes permiso para eliminar archivos en esta empresa.",
    204: "No tienes permiso para modificar cajas.",
    205: "No tienes permiso para crear cajas.",
    206: "Acceso denegado.",
    207: "No puedes eliminar tu propio usuario.",
    208: "No puedes mover elementos al Archivador.",
    300: "Debes ingresar un nombre de empresa.",
    301: "El usuario no existe.",
    302: "El usuario ya existe.",
    303: "Usuario y contrasena son obligatorios.",
    304: "No se pudo crear el usuario.",
    305: "No se pudo actualizar el usuario.",
    306: "No se pudo eliminar el usuario.",
    307: "La empresa no existe.",
    350: "La caja no existe.",
    351: "La caja pendiente no se puede mover.",
    352: "La caja tiene solapamiento de rango en destino.",
    353: "No se pudo crear la caja.",
    354: "No se pudo modificar la caja.",
    355: "No se pudo eliminar la caja.",
    400: "Tipo de documento invalido.",
    401: "Documento invalido.",
    402: "El nombre es obligatorio.",
    403: "No existe una caja cuyo rango contenga ese documento.",
    404: "No se encontro el archivo a modificar.",
    405: "No se encontro el archivo a eliminar.",
    406: "Ya existe un documento con ese numero en la empresa.",
    407: "El archivo debe ser PDF.",
    408: "No se pudo guardar el PDF.",
    409: "No se pudo modificar el archivo.",
    410: "No se pudo eliminar el archivo.",
    420: "Este documento no tiene PDF.",
    421: "PDF no encontrado.",
    422: "La seleccion de PDFs no es valida.",
    423: "No se pudo unir el PDF.",
    424: "No se encontraron PDFs para la seleccion indicada.",
    425: "Los PDFs seleccionados no estan disponibles en el servidor.",
    500: "Debes seleccionar un archivo Excel.",
    501: "El archivo Excel es invalido.",
    502: "El formato del Excel no es compatible.",
    503: "La importacion se completo con omisiones.",
    504: "No se pudo completar la importacion Excel.",
    505: "No se pudo generar el Excel.",
    550: "No seleccionaste registros.",
    551: "Debes seleccionar al menos 2 registros.",
    552: "Selecciona el registro base.",
    553: "El registro base debe estar dentro de la seleccion.",
    554: "Seleccion invalida.",
    555: "Error al unificar duplicados.",
    600: "No hay elementos seleccionados.",
    601: "Acceso invalido al modulo de archivador.",
    602: "No se pudieron mover los elementos.",
    603: "No se pudieron eliminar los elementos seleccionados.",
    680: "No se pudo cargar Auditoria.",
    681: "No se pudo cargar Movimientos.",
    682: "No se pudo cargar Usuarios.",
    683: "Movimiento no encontrado.",
    684: "No se pudo deshacer el movimiento.",
    750: "Recurso no encontrado.",
    751: "Metodo no permitido.",
    900: "Ocurrio un error interno. Intenta de nuevo.",
    901: "No se pudo guardar la informacion por conflicto de datos.",
    902: "Un texto excede el tamano permitido.",
    903: "La estructura de la base de datos no coincide con la aplicacion.",
    904: "No se pudo acceder a un archivo del servidor.",
}


def error_text(code, fallback=None, detail=None):
    message = ERROR_CATALOG.get(code, fallback or "Ocurrio un error.")
    if detail:
        return f"{message} - ERROR {code:03d} - {detail}"
    return f"{message} - ERROR {code:03d}"
