SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF COL_LENGTH('dbo.usuarios', 'creado_en') IS NULL
BEGIN
    ALTER TABLE dbo.usuarios
    ADD creado_en DATETIME2 NOT NULL
        CONSTRAINT DF_usuarios_creado_en DEFAULT (SYSDATETIME());
END;

COMMIT TRANSACTION;
